### ISSUE TITLE
Question: How was this tested on Ubuntu 20.04

### ISSUE THREAD

**Issue by BrutusTT** [ibaiGorordo/pyKinectAzure#12]
Hi,

I am trying to setup my Azure Kinect with Ubuntu 20.04 but it seems that there are no official Ubuntu binaries for the SDK yet (https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1263). Also commonly found suggestions to go for the Ubuntu 18.04 version does not work for me. 

So basically, I was wondering how I can setup the Azure Kinect on Ubuntu 20.04 ... would really like to use your tool.

Thanks in advance

**Comment by ibaiGorordo** [comment]
Hi,

To be honest I have not tested myself, but you can check how another user did it in these issues:
#5 and also there are some comments at the end of #9 (should be readable with a translator)

Hopefully, that can help you to get it working in Ubuntu.

Regards,
Ibai
