### ISSUE TITLE
Feature request: setup.py

### ISSUE THREAD

**Issue by mhmukadam** [ibaiGorordo/pyKinectAzure#16]
Hi, thank you for writing this comprehensive python wrapper over the Kinect Azure SDK. I found it extremely useful. Is it possible to add setup.py functionality so it can be used in other projects without sys path inserts?

**Comment by ibaiGorordo** [comment]
Hi, thank you for your feedback.

I have not much experience creating setup.py files, if you have experience with it, please submit a pull request and I will be happy to check it.

Ibai
