### ISSUE TITLE
Update to Body Tracking v1.1.0

### ISSUE THREAD

**Issue by MarkYu98** [ibaiGorordo/pyKinectAzure#19]
Hi, any idea or advice on updating the body tracking part to support the latest v1.1.0 API? They seems to add some new things to the DLLs. I have tried to implement it but no didn't get it work :(

**Comment by ibaiGorordo** [comment]
I haven't checked the new update yet, so I am not sure what changed. Right now I have no time for it, it will take a while until I can check it.
