### ISSUE TITLE
Anyway to crop out image for specific body parts such as head, torso?

### ISSUE THREAD

**Issue by WeiKin007** [ibaiGorordo/pyKinectAzure#22]
Looking at the original SDK documentation, I've not found a way to find pixel values in a depth/color image for specific body parts such as the head. I can relate the specific joints for the body parts using the skeleton API, but how do I get the general area of  pixels for combined joints?

**Comment by ibaiGorordo** [comment]
Hi, on the case of the head you might need to create a rectangle with a width and height that changes with the distance.

But for the joints with only two keypoints, you can use the keypoints as the corners of the rectangle to crop (you will have to check the orientation of the joint tl check if is going upwards or downwards).

For the torso for example, you can check which are top-left and bottom-right points and use them to generate a rectangle.
