### ISSUE TITLE
exampleRecording.py not working

### ISSUE THREAD

**Issue by WilliamBonilla62** [ibaiGorordo/pyKinectAzure#26]
Hi,

I am currently working on Linux Ubuntu 20.04

I trying to make work the exampleRecoring.py but I get an error which is :

![image](https://user-images.githubusercontent.com/47262366/123004015-0e0eeb00-d382-11eb-8794-8a59234a978f.png)

Which makes me believe that a library is wrongly called. This is strange since all other example worked for me.

Best Regards,

William

**Comment by ibaiGorordo** [comment]
Hi, 

There was a problem with the k4arecord module path, it was only working on Windows. I have fixed the module path settings. Let me know if it fixed the problem.

Ibai

**Comment by WilliamBonilla62** [comment]
It does work now ! 

Thank you !!!
