### ISSUE TITLE
Is possible do Body Tracking from Record?

### ISSUE THREAD

**Issue by victorc365** [ibaiGorordo/pyKinectAzure#34]
Hi I have a question, is it possible to get body tracking functionalities from a record?

**Comment by windingwind** [comment]
Hi, I'm trying to do this.

However, I failed with ctype data-type check at a strange point, maybe my code will work for you. Or, do you have any idea about this issue?
#35 

Thanks!

**Comment by ibaiGorordo** [comment]
As mentioned in #35:
"I have uploaded a major refactor that was long overdue. I have added an example "examplePlaybackBodyTracker.py" to perform body tracking in a recording that did not have body tracking enabled."
