### ISSUE TITLE
How can we use the API in this repo to get the realtime depth image infomation and turn it into .bin file? 

### ISSUE THREAD

**Issue by JiayuZou-home** [ibaiGorordo/pyKinectAzure#38]
Glad to learn your excellent jod. How can we use the API in this repo to get the realtime depth image infomation and turn it into .bin file?  @ibaiGorordo

**Comment by JiayuZou-home** [comment]
Thanks, I have found the answer~

**Comment by ibaiGorordo** [comment]
Hi, sorry for not replying earlier.

Could you share an example here or pull request in case someone has the same issue?

Thanks 
Ibai
