### ISSUE TITLE
Linux: wrong library name

### ISSUE THREAD

**Issue by mbusch-regis** [ibaiGorordo/pyKinectAzure#39]
In utils.py, lines 30 - 32, you have:

    # For non-Arm chips, first check if it is running linux
    if platform.system().lower() == 'linux':
        return 'k4abt.so'

However, this is not the correct file name. The correct name should be:

    # For non-Arm chips, first check if it is running linux
    if platform.system().lower() == 'linux':
        return 'libk4abt.so'

[utils.py.zip](https://github.com/ibaiGorordo/pyKinectAzure/files/7549632/utils.py.zip)

**Comment by VimalMollyn** [comment]
Thanks! This worked for me!

**Comment by alfredplpl** [comment]
It is nice. You should make a pull request. Or, Do I should so?

**Comment by ibaiGorordo** [comment]
Hi @alfredplpl, if you can that would be great. I have been working on other things and have had the time to test the change.

**Comment by alfredplpl** [comment]
Thanks @ibaiGorordo ! I will make a pull request for this issue.
