### ISSUE TITLE
Why I get the depth image with a 2D array?

### ISSUE THREAD

**Issue by hlyf-xs** [ibaiGorordo/pyKinectAzure#40]
Hello. I run your project on my jeston agx xavier which is a great job! But I confused that the depth image is a 2D array

**Comment by ibaiGorordo** [comment]
I am not sure about your question. What data format did you expect?

**Comment by hlyf-xs** [comment]
Ok, thanks your reply.&nbsp;&nbsp;When I used the get_depth_image() function, it returned a 2D array matrix instead of a 3D matrix




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ibai ***@***.***&gt;; 
发送时间: 2021年11月20日(星期六) 晚上8:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ibaiGorordo/pyKinectAzure] Why I get the depth image with a 2D array? (Issue #40)





 
I am not sure about your question. What data format did you expect?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ibaiGorordo** [comment]
I understand now, I think you are referring to the 3D point cloud data. You gat get it using get_pointcloud() instead of get_depth_image().

However, I have not tested it, so it might not work properly.

**Comment by hlyf-xs** [comment]
That's right! I want to get the 3D point cloud data to calculate the distance between objects and Kinect DK. But I have annother quetion how can I fuse the RGB image and the 3D point data?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ibai ***@***.***&gt;; 
发送时间: 2021年11月20日(星期六) 晚上8:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ibaiGorordo/pyKinectAzure] Why I get the depth image with a 2D array? (Issue #40)





 
I understand now, I think you are referring to the 3D point cloud data. You gat get it using get_pointcloud() instead of get_depth_image().
 
However, I have not tested it, so it might not work properly.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ibaiGorordo** [comment]
If you check the **get_pointcloud()** function, it has an optional argument called **calibration_type**, by defaults it is set to the depth camera calibration and therefore the point cloud will be relative to the depth camera. But if you pass the **_k4a.K4A_CALIBRATION_TYPE_COLOR** to the **get_pointcloud()** function, it should give you the point cloud with respect to the RGB camera.

you will have to also add `from pykinect_azure.k4a import _k4a` also in the script to get access to _k4a. I have to do change the code to be give a cleaner support, but for now I think it should work (I have not tested it).

**Comment by hlyf-xs** [comment]
Thank you very much! I get it!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ibai ***@***.***&gt;; 
发送时间: 2021年11月20日(星期六) 晚上8:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ibaiGorordo/pyKinectAzure] Why I get the depth image with a 2D array? (Issue #40)





 
If you check the get_pointcloud() function, it has an optional argument called calibration_type, by defaults it is set to the depth camera calibration and therefore the point cloud will be relative to the depth camera. But if you pass the _k4a.K4A_CALIBRATION_TYPE_COLOR to the get_pointcloud() function, it should give you the point cloud with respect to the RGB camera.
 
you will have to also add from pykinect_azure.k4a import _k4a also in the script to get access to _k4a. I have to do change the code to be give a cleaner support, but for now I think it should work (I have not tested it).
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
