### ISSUE TITLE
Typo in k4abt_types

### ISSUE THREAD

**Issue by aiwhoo** [ibaiGorordo/pyKinectAzure#41]
When specifying the list of joint names, the right eye is "rigth eye" rather than "right eye".

Just wanted to point this typo out.

I love all the work you do.

**Comment by ibaiGorordo** [comment]
Thank you for noticing! Could you submit a pull request? If you don't want it, I can fix it, but since you found the issue, I encourage you to submit the pull request.

Cheers,
Ibai

**Comment by aiwhoo** [comment]
I've created a pull request for this issue.
