### ISSUE TITLE
Error while using exampleBodySegmentation.py

### ISSUE THREAD

**Issue by Avita0207** [ibaiGorordo/pyKinectAzure#45]
Hello!
It may be difficult to understand in English from the translation, but I'm sorry.
I'm a college student who is now starting to touch Azure Kinect. I was looking for Azure Kinect to work with python and found your great library.

So, I tried using "exampleBodySegmentation.py", but the following error occurred.
![image](https://user-images.githubusercontent.com/96512030/147040890-89221d61-b6f1-41aa-81b7-dbc9c9d4f664.png)
In order to solve this problem, I saw a case of a similar error like URL in github memory before and decided to see it and put it into practice.

https://githubmemory.com/repo/ibaiGorordo/pyKinectAzure/issues/15
Here, it was said that it was solved by updating Windows and lowering the AzureKinectSDK to v10.0, so I thought I would do it, but I am in trouble because the AzureKinectSDK v10.0 can not be installed.
I would be grateful if you could tell me how to solve it as soon as possible. Thank you.

**Comment by ibaiGorordo** [comment]
Hi!

I think the problem might be different. 

- Have you installed the latest Azure Kinect Body Tracking SDK (https://docs.microsoft.com/en-us/azure/kinect-dk/body-sdk-download)?
- Do you have a Nvidia GPU in your system? (The body tracking requires Cuda DNN to be installed).
- Does the example in the Azure Kinect Body Tracking SDK work in your device?

**Comment by Avita0207** [comment]
happy New Year!

I'm sorry I couldn't reply because I've been back to my hometown for a long time.

When I checked it, Cuda DNN could not be installed.
I think that the two you have presented are completed.
Does the "Azure Kinect Body Tracking SDK example" mean "k4abt_simple_3d_viewer.exe"? If this is the case, it is working.
Also, when I installed Cuda DNN and tried it, I got an error like this. 

![image (1)](https://user-images.githubusercontent.com/96512030/148212810-05bc6dab-1a37-400a-996c-bf8eef07297f.png)

I know it's an error with no attributes, but I don't know the solution.
I'm new to python, so I'm sorry for the in
convenience, but I'd appreciate it if you could help me.

Thank you.

**Comment by Avita0207** [comment]
I'm sorry suddenly.
After installing CudaDNN, I was checking the operation again, but the example of Azure Kinect Body Tracking SDK that should have worked before did not work on the device.
When I try to open it, a window called "3D Visualization" appears, but the image of Azure Kinect is displayed, and the bone of the recognized person should be overlaid, but it does not appear as a white screen.
The question here may be a little different, but if you know the solution, please let me know.

Thank you.

**Comment by ibaiGorordo** [comment]
Sorry for the delay. There was a issue in the code. The example should work well now.

**Comment by Avita0207** [comment]
Thank you!

Thanks to you, you can now move the sample!

Thank you very much!
