### ISSUE TITLE
Why the coordinate of the depth camera is the opposite of the RGB?

### ISSUE THREAD

**Issue by hlyf-xs** [ibaiGorordo/pyKinectAzure#46]
I confused that the coordinate of the depth camera after transformed_depth() is the opposite of the RGB, for example, the depth value of the coordinate color[x][y] is depth[y][x].

**Comment by ibaiGorordo** [comment]
I cannot check it now, but it looks like the way images are stored. Where the x pixels of an image refer to the columns and the y pixels with the row.

That is why in pixel format (x,y) would be row y and column x.

Let me know if you are talking about a different issue.

**Comment by hlyf-xs** [comment]
Ok,thank you! I have understand!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ibaiGorordo/pyKinectAzure"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 下午2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ibaiGorordo/pyKinectAzure] Why the coordinate of the depth camera is the opposite of the RGB? (Issue #46)





 
I cannot check it now, but it looks like the way images are stored. Where the x pixels of an image refer to the columns and the y pixels with the row.
 
That is why in pixel format (x,y) would be row y and column x.
 
Let me know if you are talking about a different issue.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
