### ISSUE TITLE
Projecting depth image to color space using Playback API

### ISSUE THREAD

**Issue by Shihab-Shahriar** [ibaiGorordo/pyKinectAzure#47]
The transformed depth image seems to have that hexagonal artifact. Is this expected behaviour?

Here is the transformed-depth samples:
![ideal_output](https://user-images.githubusercontent.com/10344623/150248577-258498b8-548f-4c92-aa75-55bc3a40c5e6.png)
 
And here is the original color one:
![color-image](https://user-images.githubusercontent.com/10344623/150248637-0f00f57b-7cd8-4d27-980e-942d70fd2655.png)

Let me know if you need anymore info.

**Comment by ibaiGorordo** [comment]
Thanks, I missed this issue. Yes it is normal for the narrow field of view mode.
