### ISSUE TITLE
Is it possible to display the coordinates of the joint as a value?

### ISSUE THREAD

**Issue by Avita0207** [ibaiGorordo/pyKinectAzure#48]
Hello!

Thank you very much for the sample!

I would like to use this library to create a program that displays the coordinates of joints and use those coordinates to do various things.

The question is, is it possible to display joint coordinates as values ​​in this wonderful library you created?

Also, I am currently trying this and borrowed a little Sample and wrote it like this.
I will post some of them, but I am sorry for the dirty code.

	# Initialize the library, if the library is not found, add the library path as argument
	pykinect.initialize_libraries(track_body=True)

	# Modify camera configuration
	device_config = pykinect.default_configuration
	device_config.color_resolution = pykinect.K4A_COLOR_RESOLUTION_1080P
	device_config.depth_mode = pykinect.K4A_DEPTH_MODE_WFOV_2X2BINNED
	#print(device_config)

	# Start device
	device = pykinect.start_device(config=device_config)

	# Start body tracker
	bodyTracker = pykinect.start_body_tracker()

	cv2.namedWindow('Color image with skeleton',cv2.WINDOW_NORMAL)
	while True:
		
		# Get capture
		capture = device.update()

		# Get body tracker frame
		body_frame = bodyTracker.update()

		# Get the color image
		ret, color_image = capture.get_color_image()

		# Get the num bodies
		num_bodies_frame = body_frame.get_num_bodies()
		#print(num_bodies_frame)

		# Get the index map
		#body_frame_index_map = body_frame.get_transformed_body_index_map

		## Get Joint position
		for i in range(num_bodies_frame):
			num_body_frame_skeleton = body_frame.get_body_skeleton(index = i)
			num_body_frame_id = body_frame.get_body_id(index = i)
			#print(num_body_frame_id)
			for a in range(num_body_frame_id):
				get_body_joint = body_frame.get_body(bodyIdx = a)
				print(get_body_joint)`

When I ran it, I got an error like this.

`PS C:\Users\U4\pyKinectAzure\examples> python c:\Users\U4\pyKinectAzure\examples\exampleBodyTrackingColorCamera.py
Traceback (most recent call last):
  File "c:\Users\U4\pyKinectAzure\examples\exampleBodyTrackingColorCamera.py", line 54, in <module>
    print(get_body_joint)
  File "C:\Users\U4\pyKinectAzure\examples\..\pykinect_azure\k4abt\body.py", line 39, in __str__    
    f"\tposition: [{self.position.x},{self.position.y},{self.position.z}]\n"
AttributeError: 'Body' object has no attribute 'position`

If you don't mind, please let me know the solution.
I'm sorry, but I would appreciate it if you could answer as soon as possible.
Thank you!

**Comment by ibaiGorordo** [comment]
Hi, 

Thanks for letting me know. I have fixed the issue for printing the body. It should work now, you can also get the same result this way:
```
for body in body_frame.get_bodies():
    print(body)
```

However, that will print a other information like the confidence and orientation. You can use something like this to print only the position:
```
for body in body_frame.get_bodies():

    print("Body: ")
    for joint in body.joints:
		
        joint_info = f"{joint.name} position: {joint.position.x},{joint.position.y},{joint.position.z}"
        print(joint_info)
```

**Comment by Avita0207** [comment]
Thank you!

Thanks to you, I was able to do it safely! Sincerely thank. Thank you very much!
