### ISSUE TITLE
capture.get_pointcloud(): BGRA32 data unexpected + causing reshape failure?

### ISSUE THREAD

**Issue by rajkundu** [ibaiGorordo/pyKinectAzure#50]
Hello! I am trying to do some basic I/O with a very short and simple 5-second `.mkv` recording. I am simply trying to get a point cloud from a single frame of the recording.

Here is the code I am using:

```python
import numpy as np
from pykinect_azure import pykinect

# Initialize the library, if the library is not found, add the library path as argument
pykinect.initialize_libraries()

# Start playback
playback = pykinect.start_playback("test.mkv")

playback_config = playback.get_record_configuration()
print(playback_config)

# Get camera capture
while(playback.isOpened()):
	capture = playback.update()
	_, depth = capture.get_depth_image()
	_, color = capture.get_color_image()
	if(np.any(depth) and np.any(color)):
		break

capture.get_pointcloud()
```

Here is the error:
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/35236205/152913079-19c8394a-7feb-4b7a-9d3c-2839c1f91c0d.png">

Somehow, the code is finding BGRA32-formatted data in the recording. I don't really understand why, especially given the following output of printing `playback.get_record_configuration()`:
```
Record configuration: 
	color_format: 0 
	(0:JPG, 1:NV12, 2:YUY2, 3:BGRA32)

	color_resolution: 5 
	(0:OFF, 1:720p, 2:1080p, 3:1440p, 4:1536p, 5:2160p, 6:3072p)

	depth_mode: 2 
	(0:OFF, 1:NFOV_2X2BINNED, 2:NFOV_UNBINNED,3:WFOV_2X2BINNED, 4:WFOV_UNBINNED, 5:Passive IR)

	camera_fps: 2 
	(0:5 FPS, 1:15 FPS, 2:30 FPS)

	color_track_enabled: True 
	(True of False). If Color camera images exist

	depth_track_enabled: True 
	(True of False). If Depth camera images exist

	ir_track_enabled: True 
	(True of False). If IR camera images exist

	imu_track_enabled: True 
	(True of False). If IMU samples exist

	depth_delay_off_color_usec: 0 us. 
	Delay between the color image and the depth image

	wired_sync_mode: 0
	(0:Standalone mode, 1:Master mode, 2:Subordinate mode)

	subordinate_delay_off_master_usec: 0 us.
	The external synchronization timing.

	start_timestamp_offset_usec: 200244 us. 
	Start timestamp offset.
```

I am using Ubuntu 20.04, VS Code (remote/SSH into Ubuntu system), and I installed the Azure Kinect DK SDK using the `apt install` commands (I did not compile or copy any files myself). Am I doing something wrong?

The `test.mkv` file was recorded using the `k4arecorder` command line tool.

**Comment by ibaiGorordo** [comment]
Hi, sorry for the long delay.

There was an issue in the pointcloud conversion. It should work well now.
`ret, points = capture.get_pointcloud()`
