### ISSUE TITLE
Convert_2d_to_3d

### ISSUE THREAD

**Issue by ANARKHDYD** [ibaiGorordo/pyKinectAzure#53]
How to obtain 3d coordinates (x, y ,z) of a pixel (x,y) in the image.

**Comment by ibaiGorordo** [comment]
You can do `ret, points = capture.get_pointcloud()`. I haven't added the logic to transform the color also yet. If you want the colors of those 3D points you can transform the color image to the depth axis, and get the pixel colors from there.

**Comment by ibaiGorordo** [comment]
Added example with color 3D point cloud.
