### ISSUE TITLE
How do I extract depth data?

### ISSUE THREAD

**Issue by ghadaAy** [ibaiGorordo/pyKinectAzure#58]
I can't seem to find a way to extract the depth data from kinect DK.
I found a few blogs that talk about the use of getRawDepth() but it's not in Kinect DK I think.

**Comment by ibaiGorordo** [comment]
In the exampleDepthImage.py example, you can replace `get_colored_depth_image` with `get_depth_image` to get the depth image. 

You can check the [capture.py](https://github.com/ibaiGorordo/pyKinectAzure/blob/master/pykinect_azure/k4a/capture.py) script for all the possible data you can get.

**Comment by ghadaAy** [comment]
Thank you alot
