### ISSUE TITLE
How to get the original depth value?

### ISSUE THREAD

**Issue by hillaric** [ibaiGorordo/pyKinectAzure#61]
In the code, the saved depth image is the format of uint8, I want to know how to get the real depth value for this uint8 pcitures.

**Comment by ibaiGorordo** [comment]
You can use the `get_depth_image()` function instead to get the depth in millimeters. You can visualize it matplotlib to check the actual pixel depth values.
```
import matplotlib.pyplot as plt
ret, depth_image = capture.get_depth_image()
plt.imshow(depth_image)
plt.show()
```
