### ISSUE TITLE
Is it possible to convert 1024x1024 depth image to 1024x1024x3 point cloud?

### ISSUE THREAD

**Issue by JeffR1992** [ibaiGorordo/pyKinectAzure#68]
I'm running a series of experiments with the Azure Kinect at a depth resolution of 1024x1024, and am trying to figure out if it's possible to convert a 1024x1024 depth image into an 1024x1024x3 point cloud. That is, I'd like to convert each pixel in the 1024x1024 image from an depth/range into an XYZ position. Does pyKinectAzure provide functionality to achieve this? Any help would be appreciated. Thanks!

**Comment by ibaiGorordo** [comment]
Check this example:
https://github.com/ibaiGorordo/pyKinectAzure/blob/master/examples/examplePointCloud.py

Also, if you want the point cloud to have the RGB color information, check this other example:
https://github.com/ibaiGorordo/pyKinectAzure/blob/master/examples/examplePointCloud.py
