### ISSUE TITLE
k4a_transformation_depth_image_to_color_camera() is not returning RGB-D

### ISSUE THREAD

**Issue by bs97** [ibaiGorordo/pyKinectAzure#69]
Hello, 

I am trying to produce a rgb-d format image i.e. for each pixel there should be an associated depth value. Following the azure sdk (https://docs.microsoft.com/en-us/azure/kinect-dk/use-image-transformation) the transformation: k4a_transformation_depth_image_to_color_camera() should return rgb-d values. 

 The example from the examples folder: exampleTransformDepthToColor.py uses this function, however the object returned (transformed_colored_depth_image) is of shape x,y,3 (there are only rgb values for each pixel and no depth). How do I get the rgb-d values? 

Any help with this would be greatly appreciated :)

**Comment by ibaiGorordo** [comment]
That variable is the colored depth after applying the colormap, if you just want the depth you can use get_transformed_depth_image() instead:
https://github.com/ibaiGorordo/pyKinectAzure/blob/538111ccbe1c0c19151ed742e143bf32a0d90978/pykinect_azure/k4a/capture.py#L80
