### ISSUE TITLE
TypeError: shape must be a tuple  buffer_array = np.ctypeslib.as_array(buffer_pointer,shape=[image_size])

### ISSUE THREAD

**Issue by lostmj** [ibaiGorordo/pyKinectAzure#7]
I met problem with running the example. Please help me?

'''

        disable_streaming_indicator: False
        (True or False). Streaming indicator automatically turns on when the color or depth camera's are in use.

Traceback (most recent call last):
  File "exampleColorImageOpenCV.py", line 40, in <module>
    color_image = pyK4A.image_convert_to_numpy(color_image_handle)
  File "../pyKinectAzure\pyKinectAzure.py", line 490, in image_convert_to_numpy
    buffer_array = np.ctypeslib.as_array(buffer_pointer,shape=[image_size])
  File "D:\Anaconda3\lib\site-packages\numpy\ctypeslib.py", line 436, in as_array
    return array(obj, copy=False)
TypeError: shape must be a tuple
'''

**Comment by ibaiGorordo** [comment]
Hi,

I have modified the code in that function so that the shape is a tuple as mention in the output error. I think it should solve the problem. In my case both the old and the tuple shape worked, so it might be a version problem. 

But let me know if the fix worked.

Ibai
