### ISSUE TITLE
How can I cite your codes?

### ISSUE THREAD

**Issue by fw-codes-files** [ibaiGorordo/pyKinectAzure#74]
you don't have citings

**Comment by ibaiGorordo** [comment]
I have added a citation menu on the right side (cite this repository)
![Screenshot from 2022-08-19 21-10-25](https://user-images.githubusercontent.com/43162939/185615631-686447d2-257a-47ac-94a1-a568c32f903b.png)

**Comment by fw-codes-files** [comment]
Ok, I see it , thank you.Your work is very meaningful.
