### ISSUE TITLE
ERROR Installing pykinect_azure package

### ISSUE THREAD

**Issue by JSCG95** [ibaiGorordo/pyKinectAzure#75]
I'm trying to install the library from Spyder console before running one example script, but the following error message is displayed:

_>pip install pykinect_azure
Note: you may need to restart the kernel to use updated packages.
ERROR: Could not find a version that satisfies the requirement pykinect_azure (from versions: none)
ERROR: No matching distribution found for pykinect_azure__

Is that the correct way to install the package?

**Comment by ibaiGorordo** [comment]
I haven't created a python package, you will have to clone this repository as mentioned in https://github.com/ibaiGorordo/pyKinectAzure#examples
