### ISSUE TITLE
There is a typo in line 68 configuration.py, (indictaor instead of indicator)

### ISSUE THREAD

**Issue by Mikohab450** [ibaiGorordo/pyKinectAzure#76]
https://github.com/ibaiGorordo/pyKinectAzure/blob/87d722ef5b0ca97b1f595f39d395992a603e56d3/pykinect_azure/k4a/configuration.py#L68

**Comment by ibaiGorordo** [comment]
Thanks for the info, do you mind submitting a Pull Request with that change?
