### ISSUE TITLE
How to get  the skeleton data of a lying man?

### ISSUE THREAD

**Issue by 110204362** [ibaiGorordo/pyKinectAzure#80]
The K4a's body tracking can't recognize a man who is lying down on the bed. So, I can't get his skeleton data when he is lying down. Could you please help me to solve this problem?

**Comment by ibaiGorordo** [comment]
If the Kinect Body tracker isn't working, there is nothing I can do. Try to use a pose estimation deep learning model instead (something like https://github.com/ibaiGorordo/ONNX-Mobile-Human-Pose-3D), which will not give you a good pose estimation, so it might be better to change the position of the Kinect until it recognize the person.
