### ISSUE TITLE
Cannot get color_image when runing examplePlayback.py

### ISSUE THREAD

**Issue by gaolizhao** [ibaiGorordo/pyKinectAzure#83]
First step, I run exampleRecording.py to save a video. And then I run examplePlayback.py to extract info. But I fail to get color_image cause it's None.
![image](https://user-images.githubusercontent.com/24197388/205911421-a744122a-4b88-436a-a42b-583b1c58f910.png)

**Comment by ibaiGorordo** [comment]
That is because the capture for that frame had no color, so I have updated the playback example to use the ret to check if the data is correct.
